name: musinformatics
channels:
- conda-forge
- defaults
dependencies:
- conda-forge::audioread=2.1.4=py35_2
- conda-forge::blas=1.1=openblas
- conda-forge::ca-certificates=2016.8.2=3
- conda-forge::cairo=1.12.18=8
- conda-forge::certifi=2016.8.2=py35_0
- conda-forge::click=6.6=py35_0
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::cython=0.24.1=py35_0
- conda-forge::decorator=4.0.10=py35_0
- conda-forge::ffmpeg=2.8.6=2
- conda-forge::flask=0.11.1=py35_0
- conda-forge::flask-cache=0.13.1=py35_0
- conda-forge::flask-wtf=0.12=py35_0
- conda-forge::fontconfig=2.11.1=3
- conda-forge::freetype=2.6.3=1
- conda-forge::gettext=0.19.7=1
- conda-forge::glib=2.48.0=4
- conda-forge::gunicorn=19.6.0=py35_0
- conda-forge::harfbuzz=1.0.6=0
- conda-forge::icu=56.1=4
- conda-forge::itsdangerous=0.24=py35_0
- conda-forge::jinja2=2.8=py35_1
- conda-forge::joblib=0.10.0=py35_0
- conda-forge::jpeg=9b=0
- conda-forge::libffi=3.2.1=2
- conda-forge::libiconv=1.14=3
- conda-forge::libpng=1.6.24=0
- conda-forge::librosa=0.4.3=py35_0
- conda-forge::libtiff=4.0.6=6
- conda-forge::libxml2=2.9.4=0
- conda-forge::markupsafe=0.23=py35_0
- conda-forge::matplotlib=1.5.2=np111py35_6
- conda-forge::ncurses=5.9=8
- conda-forge::numpy=1.11.1=py35_blas_openblas_201
- conda-forge::openblas=0.2.18=4
- conda-forge::openssl=1.0.2h=2
- conda-forge::pango=1.40.1=0
- conda-forge::pcre=8.38=1
- conda-forge::pip=8.1.2=py35_0
- conda-forge::pixman=0.32.6=0
- conda-forge::pyparsing=2.1.7=py35_0
- conda-forge::python=3.5.2=2
- conda-forge::python-dateutil=2.5.3=py35_0
- conda-forge::pytz=2016.6.1=py35_0
- conda-forge::qt=4.8.7=0
- conda-forge::readline=6.2=0
- conda-forge::resampy=0.1.4=np111py35_0
- conda-forge::scikit-learn=0.17.1=np111py35_blas_openblas_202
- conda-forge::scipy=0.18.0=np111py35_blas_openblas_201
- conda-forge::setuptools=26.1.0=py35_0
- conda-forge::sip=4.18=py35_0
- conda-forge::six=1.10.0=py35_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=0
- conda-forge::werkzeug=0.11.10=py35_0
- conda-forge::wheel=0.29.0=py35_0
- conda-forge::x264=20131217=1
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.8=3
- gevent=1.1.2=py35_0
- greenlet=0.4.10=py35_0
- libgfortran=3.0.0=1
- mkl=11.3.3=0
- pyqt=4.11.4=py35_4
- wtforms=2.1=py35_0
- pip:
  - audioread==2.1.4
  - certifi==2016.8.2
  - cffi==1.7.0
  - click==6.6
  - cycler==0.10.0
  - cython==0.24.1
  - decorator==4.0.10
  - flask==0.11.1
  - flask-cache==0.13.1
  - flask-wtf==0.12
  - gunicorn==19.6.0
  - itsdangerous==0.24
  - jinja2==2.8
  - joblib==0.10.0
  - librosa==0.4.3
  - markupsafe==0.23
  - matplotlib==1.5.2
  - numpy==1.11.1
  - pip==8.1.2
  - pycparser==2.14
  - pyparsing==2.1.7
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - resampy==0.1.4
  - scikit-learn==0.17.1
  - scipy==0.18.0
  - setuptools==26.1.0.post20160828
  - six==1.10.0
  - soundfile==0.8.1
  - werkzeug==0.11.10
  - wheel==0.29.0
prefix: /home/colin/miniconda3/envs/musinformatics

